acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns= [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('creply/<bpk>',views.creply, name="creply")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/',include('board.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    comment = models.TextField(blank=True)
    point = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y")
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return f"{self.subject}"

class Reply(models.Model):
    b = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User
from django.contrib.auth.hashers import check_password

def chpass(request):
    u = request.user
    cp = request.POST.get("cpass")
    if check_password(cp, u.password):
        np = request.POST.get("npass")
        u.set_password(np)
        u.save()
        return redirect("acc:login")
    return redirect("acc:update")

def update(request):
    if request.method == "POST":
        u = request.user
        ue = request.POST.get("umail")
        uc = request.POST.get("ucom")
        up = request.FILES.get("upic")
        u.email, u.comment = ue, uc
        if up:
            u.pic.delete()
            u.pic = up
        u.save()
        return redirect("acc:profile")
    return render(request, "acc/update.html")

def delete(request):
    u = request.user
    ck = request.POST.get("ck")
    if check_password(ck,u.password):
        u.pic.delete()
        u.delete()
        return redirect("acc:index")
    return redirect("acc:profile")

def profile(request):
    return render(request, "acc/profile.html")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucom")
        pi = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
            return redirect("acc:login")
        except:
            pass # 마지막
    return render(request, "acc/signup.html")

def ulogout(request):
    logout(request)
    return redirect("acc:index")

def ulogin(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(request, u)
            return redirect("acc:index")
        else:
            pass # 마지막
    return render(request, "acc/login.html")

def index(request):
    context = {
        "dict" : {1:"one", 2:"two", 3:"three"}
    }
    return render(request, "acc/index.html")

board/views.py
from django.shortcuts import render, redirect
from .models import Board ,Reply
from django.utils import timezone
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")
    pg = request.GET.get("page", 1)

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
    else:
        b = Board.objects.all()

    pag = Paginator(b, 3)
    obj = pag.get_page(pg)

    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw
    }
    return render(request, "board/index.html", context)


def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != request.user:
        # 혼내줘야함
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect("board:detail", bpk)

    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, content=c, writer=request.user, pubdate=timezone.now()).save()
        return redirect("board:index")
    return render(request, "board/create.html")

def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == request.user:
        b.delete()
    else:
        pass # 무조건 공격!
    return redirect("board:index")
    

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    Reply(b=b, comment=c, replyer=request.user).save()
    return redirect("board:detail", bpk)

def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        pass # 혼내줌
    return redirect("board:detail", bpk)


def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()

    context = {
        "b" : b,
        "rset" : r
    }
    return render(request, "board/detail.html", context)

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}

    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">WELCOME TO MY WEBSITE!</h1>
            <p class="col-md-8 fs-4">Hello everyone! My first django project 💥 </p>
        </div>
    </div>
    {% for k,v in dict.items %} 
        {{k}} {{v}} <br> 
    {% endfor %}

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>LOGIN PAGE</b></h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname" class="form-control mt-5" placeholder="INPUT USERNAME">
        <input type="password" name="upass" class="form-control mt-3" placeholder="INPUT PASSWORD">

        <div class="text-end mt-4">
            <button class="btn btn-dark btn-lg">LOGIN</button>
        </div>
    </form>
    

{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ user }}'s PROFILE</b></h1>

        <div class="row">
            <div class="col-sm-7 text-center" style="margin: auto;">
                <img src="{{ user.getpic }}" class="rounded-circle" width="80%">
            </div>
            <div class="col-sm-5">

                <label class="form-label mt-5">USERNAME</label>
                <input type="text" value="{{user}}" disabled class="form-control">
        
                <label class="form-label mt-4">POINT</label>
                <input type="text" value="{{user.point}} P" disabled class="form-control">
        
                <label class="form-label mt-4">EMAIL</label>
                <input type="text"  value="{{user.email}}" disabled class="form-control">

                <label class="form-label mt-4">COMMENT</label>
                <textarea class="form-control" disabled>{{ user.comment }}</textarea>
            </div>
        </div>

        <div class="mt-5 text-end">
            <a href="{% url 'acc:update' %}" class="btn btn-dark btn-lg">정보수정</a>
            <!-- modal trigger button -->
            <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                계정삭제
            </button>
        </div>
        
    </div>


    <!-- Modal -->
    <form method="post" action="{% url 'acc:delete' %}">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">계정 삭제 알림창</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <label class="form-label">패스워드 확인</label>
                        <input type="password" name="ck" class="form-control">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-danger">삭제</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>SIGNUP PAGE</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="form-label mt-5">USERNAME</label>
        <input type="text" name="uname" class="form-control">

        <label class="form-label mt-4">PASSWORD</label>
        <input type="passowrd" name="upass" class="form-control">

        <label class="form-label mt-4">CHECK PASSWORD</label>
        <input type="passowrd" name="ckpass" class="form-control">

        <label class="form-label mt-4">USERPIC</label>
        <input type="file" name="upic" class="form-control">

        <label class="form-label mt-4">COMMENT</label>
        <textarea class="form-control" name="ucom"></textarea> 

        <div class="text-end mt-4">
            <button class="btn btn-dark btn-lg">회원가입</button>
        </div>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>UPDATE PAGE</b></h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- username 은 변경불가하도록 disabled 유지 -->
        <label class="form-label mt-5">USERNAME</label>
        <input type="text" disabled value="{{user}}" class="form-control">

        <label class="form-label mt-4">EMAIL</label>
        <input type="text" name="umail" value="{{user.email}}" class="form-control">

        <label class="form-label mt-4">USERPIC</label>
        <input type="file" name="upic" class="form-control">

        <label class="form-label mt-4">COMMENT</label>
        <textarea class="form-control" name="ucom">{{ user.comment }}</textarea> 

        <div class="text-end mt-4">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                패스워드변경
            </button>
            <button class="btn btn-dark btn-lg">수정완료</button>
        </div>
    </form>



    <!-- Modal -->
    <form method="post" action="{% url 'acc:chpass' %}">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel"><b>패스워드 변경창</b></h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <input type="password" name="cpass" placeholder="CURRENT PASSWORD" class="form-control">
                        <input type="password" name="npass" placeholder="NEW PASSWORD" class="form-control mt-3">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-primary">변경</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SH WORLD</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    </head>
    <body>
        {% if user.is_authenticated %}
        <!-- 인증된 사용자 메뉴바 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0);">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:index' %}">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">BOARD</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% else %}
        <!-- 익명의 사용자 메뉴바 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0);">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:index' %}">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}

        <div class="container mt-5 mb-5">
            {% block con %}


            {% endblock %}
        </div>
        

        <style>
            .nav-item{
                font-size: 20px;
                font-weight: bold;
                margin-left: 10px;
            }
            .form-control{
                font-weight: bold;
                font-size: 20px;
            }
            .form-label{
                font-weight: bold;
                font-size: 20px;
            }
        </style>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    </body>
</html>

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글 생성</b></h1>

    <form method="post">
        {% csrf_token %}
        <input class="form-control mt-5" name="sub" placeholder="INPUT SUBJECT">
        <input class="form-control mt-4 mb-4" value="{{ user }}" disabled>
        <textarea class="form-control" name="con" style="height: 250px;" placeholder="INPUT CONTENT"></textarea>

        <div class="text-end mt-4">
            <button class="btn btn-dark">생성하기</button>
        </div>
    </form>

{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>{{ b.subject }}</b></h1>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 250px;" disabled>{{ b.content }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ b.writer.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>written by <b>{{ b.writer }}</b></h4>
            </div>
            <div class="text-end mt-2">
                {{ b.pubdate | date:'Y년 n월 j일 / H:i' }}
            </div> 
        </div>
    </div>

    <div class="text-end mt-4">
        <a href="{% url 'board:index' %}" class="btn btn-dark">메인</a>
        <a href="#" class="btn btn-primary">좋아요</a>
        {% if user == b.writer %}
            <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                삭제
            </button>
        {% endif %}
    </div>

    <hr>

        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row mt-4 mb-4">
                <div class="col-sm-10">
                    <input type="text" name="com" class="form-control" placeholder="댓글 내용을 입력해주세요">
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
                </div>
            </div>
        </form>
        
    <hr>

    {% for i in rset %}
        <div class="row mt-4 text-center">
            <div class="col-sm-3">
                <img src="{{ i.replyer.getpic }}" width="80%">
                <div class="mt-3">
                    <b>{{ i.replyer }}</b>
                </div>
            </div>
            <div class="col-sm-9">
                <textarea class="form-control" style="height: 100px;" disabled>{{ i.comment }}</textarea>
                {% if user == i.replyer %}
                    <div class="text-end mt-4">
                        <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger">댓글삭제</a>
                    </div>
                {% endif %}
            </div>
        </div>
    {% empty %}
        <h4 class="text-center">첫번째 댓글을 달아주세요</h4>
    {% endfor %}





    <!-- 삭제모달창 -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">게시글 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'board:delete' b.id %}" type="button" class="btn btn-danger">삭제하기</a>
                </div>
            </div>
        </div>
    </div>






{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}
    {% load mathfilters %}
    <h1><b>SH BOARD</b></h1>

    <div class="text-end">
        <a class="btn btn-dark" href="{% url 'board:create' %}">WRITE</a>
    </div>

    <table class="table table-hover mt-4">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">WRITER</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            
            {% for i in bset %}
                <tr>
                    <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                    <td><a href="{% url 'board:detail' i.id %}" class="sub">{{ i.subject }}</a></td>
                    <td>{{ i.writer }}</td>
                    <td>{{ i.content |truncatewords:10 }}</td>
                    <td>0</td>
                </tr>
            
            {% empty %}
                <tr class="text-center">
                    {% if kw %}
                        <th colspan="5"><h4>검색결과가 없습니다 😉</h4></th>
                    {% else %}
                        <th colspan="5"><h4>첫번째 게시글을 작성해주세요 💦</h4></th>
                    {% endif %}
                </tr>
            {% endfor %}
        
        </tbody>
    </table>



    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          
            {% if bset.has_previous %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}">처음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}">이전</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">처음</a></li>
                <li class="page-item disabled"><a class="page-link">이전</a></li>
            {% endif %}

          
            {% for i in bset.paginator.page_range %}
                {% if bset.number|add:2 >= i and i >= bset.number|sub:2 %}
                    <li class="page-item {% if bset.number == i %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}
            
            {% if bset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}">다음</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">마지막</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">다음</a></li>
                <li class="page-item disabled"><a class="page-link">마지막</a></li>
            {% endif %}

        </ul>
    </nav>

    <form>
        <div class="mt-4 row">
            <div class="col-sm-2">
                <select name="cate" class="form-select">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input type="text" name="kw" value="{{kw}}" class="form-control">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
            <div class="col-sm-1">
                <a class="btn btn-dark" href="{% url 'board:index' %}" style="width: 100%;">리셋</a>
            </div>
        </div>
    </form>


    <style>
        .sub {
            text-decoration: none;
            color: black;
            font-weight: bold;
        }
        .sub:hover{
            color:brown;
        }
    </style>






{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <h1><b>게시글 수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <input class="form-control mt-5" name="sub" value="{{b.subject}}" placeholder="INPUT SUBJECT">
        <input class="form-control mt-4 mb-4" value="{{ user }}" disabled>
        <textarea class="form-control" name="con" style="height: 250px;" placeholder="INPUT CONTENT">{{b.content}}</textarea>

        <div class="text-end mt-4">
            <button class="btn btn-dark">수정완료</button>
        </div>
    </form>

{% endblock %}